esphome:
  name: fingerbot
  friendly_name: Fingerbot

esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "YX1wNnN4U8eJcz58K1IMCYIcUc2xIbSsd02sLdtK1x0="

ota:
  password: "eb48aa0968f3ea46261007b3253946e1"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Fingerbot Fallback Hotspot"
    password: "bpeVfJAAUlf3"

captive_portal:

servo:
  - id: finger_servo
    output: servo_output
    transition_length: 0.5s

output:
  - platform: esp8266_pwm
    id: servo_output
    pin: GPIO2
    frequency: 50 Hz

button:
  - platform: template
    name: "Mode Poussoire"
    on_press:
      then:
        - servo.write:
            id: finger_servo
            level: !lambda 'return id(press_distance).state / 100.0;'
        - delay: !lambda "return id(press_duration).state;"
        - servo.write:
            id: finger_servo
            level: -1
      
switch:
  - platform: template
    name: "Mode Switch"
    turn_on_action:
      then:
        - servo.write:
            id: finger_servo
            level: !lambda 'return id(press_distance).state / 100.0;'
    turn_off_action:
        - servo.write:
            id: finger_servo
            level: -1    

number:
  - platform: template
    id: press_distance
    name: Press Distance
    min_value: -100
    initial_value: -60
    max_value: 100
    step: 1
    mode: box
    optimistic: true

       
      
  - platform: template
    id: press_duration
    name: Press Duration
    min_value: 500
    initial_value: 500
    max_value: 5000
    step: 100
    mode: box
    optimistic: true
  
  

  